[package]
name = "rusty-calculator"
version = "1.0.1"
authors = ["Liam Cole (LiamTheIron)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
